package kib.project.fast.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val LazySunday30 = Color(0xFF473025)
val LazySunday20 = Color(0xFFAC8061)
val LazySunday10 = Color(0xFFE2C7BB)

val ChocChip30 = Color(0xFFE9A975)
val ChocChip20 = Color(0xFFC47F4C)
val ChocChip10 = Color(0xFF49302F)
val ChocChipText10 = Color(0xFF332120)

val ChocChip30Dark = Color(0xFF49302F)
val ChocChip20Dark = Color(0xFFC47F4C)
val ChocChip10Dark = Color(0xFFE9A975)
val ChocChipText10Dark = Color(0xFFEfC29E)

val cardCollapsedBackgroundColor = Color(0xFFFEFFFD)
val cardExpandedBackgroundColor = Color(0xFFFFDA6D)

val md_theme_light_primary = Color(0xFF984719)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBCC)
val md_theme_light_onPrimaryContainer = Color(0xFF351000)
val md_theme_light_secondary = Color(0xFFA53C00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCD)
val md_theme_light_onSecondaryContainer = Color(0xFF360F00)
val md_theme_light_tertiary = Color(0xFF5156A9)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0E0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF070764)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF001849)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF001849)
val md_theme_light_surfaceVariant = Color(0xFFF4DED5)
val md_theme_light_onSurfaceVariant = Color(0xFF52443D)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_inverseOnSurface = Color(0xFFEEF0FF)
val md_theme_light_inverseSurface = Color(0xFF002B75)
val md_theme_light_inversePrimary = Color(0xFFFFB693)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF984719)
val md_theme_light_outlineVariant = Color(0xFFD7C2B9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB693)
val md_theme_dark_onPrimary = Color(0xFF561F00)
val md_theme_dark_primaryContainer = Color(0xFF7A3001)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCC)
val md_theme_dark_secondary = Color(0xFFFFB597)
val md_theme_dark_onSecondary = Color(0xFF591D00)
val md_theme_dark_secondaryContainer = Color(0xFF7E2C00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCD)
val md_theme_dark_tertiary = Color(0xFFBFC2FF)
val md_theme_dark_onTertiary = Color(0xFF212578)
val md_theme_dark_tertiaryContainer = Color(0xFF393D8F)
val md_theme_dark_onTertiaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001849)
val md_theme_dark_onBackground = Color(0xFFDBE1FF)
val md_theme_dark_surface = Color(0xFF001849)
val md_theme_dark_onSurface = Color(0xFFDBE1FF)
val md_theme_dark_surfaceVariant = Color(0xFF52443D)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C2B9)
val md_theme_dark_outline = Color(0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(0xFF001849)
val md_theme_dark_inverseSurface = Color(0xFFDBE1FF)
val md_theme_dark_inversePrimary = Color(0xFF984719)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB693)
val md_theme_dark_outlineVariant = Color(0xFF52443D)
val md_theme_dark_scrim = Color(0xFF000000)